apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: ct-spread
spec:
  cpu:
    preferredCPUTopology: preferSpread
    spreadOptions:
      across: CoresThreads
      ratio: 3